# SPDX-FileCopyrightText: 2018-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-3.0-or-later

# This is the minimum version number required.
fastlane_version "2.58.0"

skip_docs

## public lanes

desc "Upload Alpha version to play store"
lane :uploadAlphaToPlayStore do |options|
    upload_to_play_store(
        skip_upload_images: true,
        skip_upload_aab: true,
        skip_upload_changelogs: true,
        skip_upload_metadata: true,
        skip_upload_screenshots: true,
        track: 'alpha',
        apk: "/home/androiddaily/apks-talk/android-talk-" + options[:version] + ".apk",
    )
end

desc "Upload Comunica GOV.AO release bundle to Play Console internal testing track"
lane :uploadComunicaInternal do
    upload_to_play_store(
        track: 'internal',
        aab: 'app/build/outputs/bundle/comunicaGplayRelease/app-comunica-gplay-release.aab',
        skip_upload_images: true,
        skip_upload_screenshots: true,
        skip_upload_changelogs: true,
        skip_upload_metadata: true,
    )
end
